# spring boot client config
server.url=http://localhost
server.port=8080

# data source config
rds.endpoint.url=acnh-flower-hybrid-genetics.cbe3cageqd73.us-east-1.rds.amazonaws.com
rds.database=hybrid_genes
rds.port=3306

spring.datasource.url=jdbc:mysql://${rds.endpoint.url}:${rds.port}/${rds.database}
spring.datasource.username=mikamarisol
spring.datasource.password=fernisle
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# maps rds to object
spring.jpa.hibernate.ddl-auto=update 
